Bookers2/config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: 'homes_about'
 ## get 'users/show'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :post_images
  end

Bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
      validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
    attachment :profile_image
    
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :name, length: { maximum: 20 }
    validates :name, length: { minimum: 2 } 
    validates :introduction, length: { maximum: 50 }
end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   ## before_action :authenticate_user!,except: [:top]
      before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end
end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update]
    
  def new
  @book = Book.new

  end

  def create
    @user = current_user
    @book = Book.new(book_params) 
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "form,successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render "index"    
    end
  end

  def index
        @books = Book.all
        @book = Book.new
        @user = current_user

  end

  def show
        @book = Book.find(params[:id])
        @book_new = Book.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
   
  end
  
  def edit
        @book = Book.find(params[:id])
  end
  
  def update
        @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "form,successfully"
        redirect_to book_path(@book.id)
    else
      @books = Book.all
      render "edit"
    end
  end
  
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user == current_user
  end
end

Bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
   def top
      
   end
   
   def about
      
   end
   
end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  before_action :correct_user,   only: [:edit, :update]
  
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @users = User.all
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    @user.save
    if @user.update(user_params)
       flash[:notice] = "form,successfully"
       redirect_to user_path(@user.id)
    else
      @user = current_user
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) unless @user == current_user
    end
end

Bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers2/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers2/app/helpers/users_helper.rb
module UsersHelper
end

Bookers2/app/views/books/edit.html.erb
    <main>
<div class="col-md-9 offset-md-3">
  
<% if @book.errors.any? %>
  <p><%= @book.errors.count %>件のerrorが発生しました</p>
  <% @book.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

  <h1>Editing Book</h1>
  <h1>Book detail</h1>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path(@book) %>
<a class="Back" href="/books">Back</a>
</div>
    </main>

Bookers2/app/views/books/index.html.erb
    <main>
    
    <div class="container px-5 px-sm-0">
<div class="row">
    <div class="col-md-3">
        <h2>User Info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
                <th>name</th>
                <th><%= @user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <h4>
        <%= link_to "", edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
    </h4>
        <tr></tr>
<h2 class="mt-3">New book</h2>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

    </div>

<div class="col-md-8 offset-md-1">


    <table>
        <thead>
        <tr>
            <th>     </th>
        <th>Title</th>
        <th>Body</th>
        </tr>
        </thead>
        
        <% @books.each do |book| %>
    <tr>
        <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
            <% end %> 
        </td>

        <td>
            <%= link_to book.title, book_path(book) %>
        </td>
        <td>
            <%= book.body %>
        </td>
    </tr>
        <% end %>
    </table>
        
</div>
</div></div>
    </main>

Bookers2/app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :tite %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

Bookers2/app/views/books/show.html.erb
    
    <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">
            <h2>User Info</h2>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
              <table class="table">
                  <tbody>
                      <tr></tr>
                      <tr>
                          <th>name</th>
                          <th><%= @book.user.name %></th>
                       </tr>
                      <tr>
                          <th>introduction</th>
                          <th><%= @book.user.introduction %></th>
                      </tr>
                  </tbody>
              </table>
    <h4>
        <%= link_to "", edit_user_path(@book.user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  </h4>
            <h2 class="mt-3">New book</h2>
                <% if @book_new.errors.any? %>
              <%= @book_new.errors.count %>件のエラーが発生しました
              <% @book_new.errors.full_messages.each do |message| %>
                <%= message %>
              <% end %>
            <% end %>
            <%= form_with model: @book_new, local:true do |f| %>
              <h4>Title</h4>
              <%= f.text_field :title %>
              <h4>Opinion</h4>
              <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
            <% end %>
          </div>
  
        <div class="col-md-8 offset-md-1">
          <h1>Book detail</h1>
              <table>
                  <thead>
                  <tr>
                  <th>　　</th>
                  <th>Title</th>
                  <th>Body</th>
                  </tr>
                  </thead>
                  
              <tr>
                  <td>
                  <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                  <%= @book.user.name %>
                  <% end %>
                  </td>
                  <td>
                      <%= @book.title %>
                  </td>
                  <td>
                      <%= @book.body %>
                  </td>
                  <td>　　　　</td>
                  <td>
                      <% if @book.user == current_user %>
                      <%= link_to "Edit", edit_book_path(@book) %>
                      <% end %>
                  </td>
                  <td>
                      <% if @book.user == current_user %>
                      <%= link_to "Destroy", book_path(@book), method: :delete %>
                      <% end %>
                  </td>
                  
              </tr>
    
              </table>
                  
        </div>
  </div>
</div>

Bookers2/app/views/homes/about.html.erb
<h1>Welcome to <i class="fas fa-book">
</i>Bookers!</h1>

Bookers2/app/views/homes/top.html.erb
<h1>welcome to 

<i class="fas fa-book">
</i>

Bookers !!</h1>

<br>



you can share and exchange your opinions , inpressions , and emotions
<br>

about various books!

              <%= link_to "log in", new_user_session_path, class: 'nav-link text-dark' %>
              
              <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-dark' %>

Bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to "Bookers", root_path, class: 'nav-link text-dark' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home", user_path(current_user.id), class: 'nav-link text-dark fas fa-home' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
              
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'nav-link text-dark fas fa-home' %>
            </li>
            <li class="nav-item">
              <%= link_to "About",  homes_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "sign Up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
     <%= flash[:notice] %>
    <main class="mb-auto">
    <%= yield %>
    </main>
</html>

Bookers2/app/views/users/edit.html.erb
<h2>User info</h2>
<% if @user.errors.any? %>
<p><%= @user.errors.count %>件のエラーが発生しました</p>
<% @user.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>
<% end %>


<%= form_with model:@user, local:true do |f| %>
<h1>name</h1>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
  
  <h1>image</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  
  <h1>introduction</h1>
    <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction"%>
  <%= f.submit " Update User" %>
<% end %>

Bookers2/app/views/users/index.html.erb
    <main>
    
    <div class="container px-5 px-sm-0">
<div class="row">
    <div class="col-md-3">
        <h2>User Info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
                <th>name</th>
                <th><%= @user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <h4>
        <%= link_to "", edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
    </h4>
        <tr></tr>
<h2 class="mt-3">New book</h2>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

    </div>

<div class="col-md-8 offset-md-1">


    <table>
        <thead>
        <tr>
        <th>Title</th>
        <th>Body</th>
        </tr>
        </thead>
        
        <% @users.each do |user| %>
    <tr>
        <td>
        <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
        </td>

        <td>
            <%= user.name %>
        </td>
        <td>
            <%= link_to "Show", user_path(user) %>
        </td>
    </tr>
        <% end %>
    </table>
</div>
</div>
</div>
    </main>

Bookers2/app/views/users/show.html.erb
<%= flash[:success] %>
    
    <div class="container px-5 px-sm-0">
<div class="row">
    <div class="col-md-3">
        <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
                <th>name</th>
                <th><%= @user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <h4>
        <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog'%>
    </h4>
        <tr></tr>
<h2 class="mt-3">New book</h2>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
  <% end %>

    </div>

<div class="col-md-8 offset-md-1">


    <table>
        <thead>
        <tr>
        <th>Title</th>
        <th>Body</th>
        </tr>
        </thead>
        
        <% @books.each do |book| %>
    <tr>
        <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
         <% end %>
        </td>

        <td>
            <%= link_to book.title, book_path(book) %>
        </td>
        <td>
            <%= book.body %>
        </td>
    </tr>
        <% end %>
    </table>
        </div></div>
</div>